export const SET_MONTHLY_SALARY = 'SET_MONTHLY_SALARY';

export const SET_WORKING_PER_WEEK = 'SET_WORKING_PER_WEEK';
export const SET_WORKING_PER_DAY = 'SET_WORKING_PER_DAY';
export const SET_START_TIME = 'SET_START_TIME';
export const SET_CLOSING_TIME = 'SET_CLOSING_TIME';
export const SET_PAYDAY = 'SET_PAYDAY';
export const SET_CALC_MODE = 'SET_CALC_MODE';

export const SET_SHOW_SETTING_MODAL = 'SET_SHOW_SETTING_MODAL';